
stages:
  - build
  - xcframework

build_simulator_archive:
  stage: build
  script:
    - xcodebuild archive \
        -scheme RideGuideFramework \
        -destination "generic/platform=iOS Simulator" \
        -archivePath ../output/RideGuideFramework-Sim \
        SKIP_INSTALL=NO \
        BUILD_LIBRARY_FOR_DISTRIBUTION=YES
  artifacts:
    paths:
      - ../output/RideGuideFramework.xcarchive

  timeout: 1h  # Set the timeout to 1 hour
